# Site settings
email: "iuserock0@gmail.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-20996874-1"
comments: true

# SEO settings
title: "lzbob is me"
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: "Zheng"
profile_img: /assets/images/profile.jpg
profile: "Zheng (lzbob) was born in Beijing, China, and moved to Unite States, have been Phoenix 4 years, and currently living in Seattle and working @Grab. He is not fat, just a ball."
social:
  github: https://github.com/zheng-liu-seattle

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
